### ISSUE TITLE
apple pyttsx3.init() not working

### ISSUE THREAD

**Issue by toChaim** [nateshmbhat/pyttsx3#1]
I have a new apple mac book pro os version 10.12.5. I tried following the instruction. Pip3 install seemed to work. Import ran no errors. The next command pyttsx3.init() resulted in 
```
>>> engine = pyttsx3.init()
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyttsx3/__init__.py", line 44, in init
    eng = _activeEngines[driverName]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyttsx3/__init__.py", line 46, in init
    eng = Engine(driverName, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyttsx3/engine.py", line 52, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyttsx3/driver.py", line 75, in __init__
    self._module = importlib.import_module(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pyttsx3/drivers/nsss.py", line 10, in <module>
    class NSSpeechDriver(NSObject):
objc.BadPrototypeError: Objective-C expects 1 arguments, Python argument has 2 arguments for <unbound selector initWithProxy of NSSpeechDriver at 0x109202238>
```
Any help or advice would be most useful.
Thanks for this project.

**Comment by toChaim** [comment]
Forgot to say I am using python Python 3.6.1

**Comment by YutingYou** [comment]
get the same error message, mac os , python 3.5

**Comment by deehzee** [comment]
I get the same error on Python 3.6.2 and MacOS Sierra 10.12.6

**Comment by CaptStephan** [comment]
I am having the same issue with MacOS Sierra 10.12.6 and Python 3.6.0 :: Anaconda 4.3.1 (x86_64).

Has anyone sorted this out?

**Comment by mwie** [comment]
I found a solution: Because of changes in PyObjC (v3.1 up?!) you have to add

__@objc.python_method__

as an decorator before some of the methods of class NSSpeechDriver in the file pyttsx3/drivers/nsss.py as noted here:

@objc.python_method
def initWithProxy(self, proxy):

@objc.python_method
def say(self, text):

@objc.python_method
def _toVoice(self, attr):

@objc.python_method
def getProperty(self, name):

@objc.python_method
def setProperty(self, name, value):

I used "trial and error" to find the methods I had to decorate.
Also I had to remove the conversion to unicode in the "say" method, from 
self._tts.startSpeakingString_(unicode(text))

to

__self._tts.startSpeakingString_(text)__

Before I removed the conversion to unicode the execution stopped at this line without an error.

**Comment by toChaim** [comment]
thanks. Great work.
I tried it and it works for me too. Thank you very much.
Did Check to see if that line works in python2? If you didn't I can do that in the next couple of days. 
That last one sounds like a python2 vs python3 issue. In python2 text is ascii and in python3 text is unicode. If it doesn't you can add a check for python version. 
After checking if this stuff works in python2 please make a pull request.

**Comment by nateshmbhat** [comment]
@toChaim i would be very happy if you do a pull request on this 👍

**Comment by toChaim** [comment]
You did the work you should get the credit. 
That said if you want me to I will check python2 and do a pull request tonight.

**Comment by nateshmbhat** [comment]
Thank you so much :) ya pls do a pull request. Lot of people are having the same problem.

**Comment by mwie** [comment]
I have litte time today. No problem, you can check python2 and do the pull request, if you will! I‘m happy it worked for others too!

**Comment by toChaim** [comment]
@nateshmbhat if you could take a look at the pull request when you get a chance. Tell us if something needs to be changed, or if we need more testing. I am eager to have this change in the code and this issue closed.
Thanks
Chaim

**Comment by nateshmbhat** [comment]
I have merged your pull request . Hope you have checked it . I don't have an apple device to check it though .

**Comment by toChaim** [comment]
I did. Thanks.

**Comment by slimdy** [comment]
I have this problem too . it doesn't work for me.  I install the new pyttsx3. but it still doesn't work .
By the way ,I got this problem on Python 3.6.2 and MacOS Sierra 10.13.1

**Comment by slimdy** [comment]
OK! I solve the issue by using 'pip install pyobjc'.  I think this problem is related to the new MacOS Sierra 10.13.1

**Comment by MegaDestro** [comment]
I own a MacBook Air M1 8GB, 256GB
MacOS 14 beta 
Python v3.9.9 

Whenever I try to run the engine.say command I get the following error:


Traceback (most recent call last):
  File "/Users/harshkumar/Desktop/Coding/noname/virtenv/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/Users/harshkumar/.pyenv/versions/3.9.9/lib/python3.9/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/harshkumar/Desktop/Coding/noname/test.py", line 2, in <module>
    engine = pyttsx3.init()
  File "/Users/harshkumar/Desktop/Coding/noname/virtenv/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/Users/harshkumar/Desktop/Coding/noname/virtenv/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Users/harshkumar/Desktop/Coding/noname/virtenv/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/Users/harshkumar/.pyenv/versions/3.9.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/harshkumar/Desktop/Coding/noname/virtenv/lib/python3.9/site-packages/pyttsx3/drivers/nsss.py", line 2, in <module>
    from Foundation import *
  File "/Users/harshkumar/Desktop/Coding/noname/virtenv/lib/python3.9/site-packages/objc/_lazyimport.py", line 181, in __getattr__
    raise AttributeError(name)
AttributeError: <FBSSceneTransitionContext>

**Comment by MegaDestro** [comment]
I have already run the command :
pip3 install pyobjc

**Comment by Fledermaus-20** [comment]
I have the same problem

**Comment by susanarebollo** [comment]
Hi,

I have a MacBook Pro with Chip M2 and Someone 14.0 and I had the same problem.

I've solved it installing the version 9.0.1 of pyobjc: pip install pyobjc==9.0.1

Then, this code finally works and sounds:

`def speak(message):

    # turn on pyttsx3
    engine = pyttsx3.init()

    # say message with voice
    engine.say(message)
    engine.runAndWait()


speak("Hi world")`

**Comment by hololeo** [comment]
i am on M1 mac 2020, i also got this to work doing the following

```
pip3 install pyobjc==9.0.1
pip3 install pyttsx3

then i created speak.py
import pyttsx3
engine = pyttsx3.init()
engine.say("I will speak this text")
engine.runAndWait()

> python3 speak.py
```

**Comment by YichenMigaloo** [comment]
> Hi,
> 
> I have a MacBook Pro with Chip M2 and Someone 14.0 and I had the same problem.
> 
> I've solved it installing the version 9.0.1 of pyobjc: pip install pyobjc==9.0.1
> 
> Then, this code finally works and sounds:
> 
> `def speak(message):
> 
> ```
> # turn on pyttsx3
> engine = pyttsx3.init()
> 
> # say message with voice
> engine.say(message)
> engine.runAndWait()
> ```
> 
> speak("Hi world")`

Thank you soooo much!!!! I've been stuck here for an hour!!

**Comment by Arav-Shakya** [comment]
If any one os facing **NameError:** name 'objc' is not defined. Did you mean: 'object'?**
and if you are on mac then I got you. 

go to your venv and find nsss.py it will be in `lib>python>pyttsx3>drivers>nsss.py`

And what we are doing is we are replacing super() with objc.super()

**NOW JUST REMOVE ALL THE CODE FROM NSSS.PY AND JUST PASTE MINE**

`
from Foundation import *
from Foundation import NSObject
from AppKit import NSSpeechSynthesizer
from PyObjCTools import AppHelper
from ..voice import Voice
import objc


def buildDriver(proxy):
    return NSSpeechDriver.alloc().initWithProxy_(proxy)


class NSSpeechDriver(NSObject):
    @objc.python_method
    def initWithProxy_(self, proxy):
        self = objc.super(NSSpeechDriver, self).init()
        if self:
            self._proxy = proxy
            self._tts = NSSpeechSynthesizer.alloc().initWithVoice_(None)
            self._tts.setDelegate_(self)
            # default rate
            self._tts.setRate_(200)
            self._completed = True
        return self

    def destroy(self):
        self._tts.setDelegate_(None)
        del self._tts

    def onPumpFirst_(self, timer):
        self._proxy.setBusy(False)

    def startLoop(self):
        NSTimer.scheduledTimerWithTimeInterval_target_selector_userInfo_repeats_(
            0.0, self, 'onPumpFirst:', None, False)
        AppHelper.runConsoleEventLoop()

    def endLoop(self):
        AppHelper.stopEventLoop()

    def iterate(self):
        self._proxy.setBusy(False)
        yield

    @objc.python_method
    def say(self, text):
        self._proxy.setBusy(True)
        self._completed = True
        self._proxy.notify('started-utterance')
        self._tts.startSpeakingString_(text)

    def stop(self):
        if self._proxy.isBusy():
            self._completed = False
        self._tts.stopSpeaking()

    @objc.python_method
    def _toVoice(self, attr):
        try:
            lang = attr['VoiceLocaleIdentifier']
        except KeyError:
            lang = attr['VoiceLanguage']
        return Voice(attr['VoiceIdentifier'], attr['VoiceName'],
                     [lang], attr['VoiceGender'],
                     attr['VoiceAge'])

    @objc.python_method
    def getProperty(self, name):
        if name == 'voices':
            return [self._toVoice(NSSpeechSynthesizer.attributesForVoice_(v))
                    for v in list(NSSpeechSynthesizer.availableVoices())]
        elif name == 'voice':
            return self._tts.voice()
        elif name == 'rate':
            return self._tts.rate()
        elif name == 'volume':
            return self._tts.volume()
        else:
            raise KeyError('unknown property %s' % name)

    @objc.python_method
    def setProperty(self, name, value):
        if name == 'voice':
            # vol/rate gets reset, so store and restore it
            vol = self._tts.volume()
            rate = self._tts.rate()
            self._tts.setVoice_(value)
            self._tts.setRate_(rate)
            self._tts.setVolume_(vol)
        elif name == 'rate':
            self._tts.setRate_(value)
        elif name == 'volume':
            self._tts.setVolume_(value)
        else:
            raise KeyError('unknown property %s' % name)

    @objc.python_method
    def save_to_file(self, text, filename):
        url = Foundation.NSURL.fileURLWithPath_(filename)
        self._tts.startSpeakingString_toURL_(text, url)

    def speechSynthesizer_didFinishSpeaking_(self, tts, success):
        if not self._completed:
            success = False
        else:
            success = True
        self._proxy.notify('finished-utterance', completed=success)
        self._proxy.setBusy(False)

    def speechSynthesizer_willSpeakWord_ofString_(self, tts, rng, text):
        self._proxy.notify('started-word', location=rng.location,
                           length=rng.length)
`

And if you are on global then do the same find nsss.py and replace its code and thank me later :)

**Comment by Yashsaini25** [comment]
> If any one os facing **NameError:** name 'objc' is not defined. Did you mean: 'object'?** and if you are on mac then I got you.
> 
> go to your venv and find nsss.py it will be in `lib>python>pyttsx3>drivers>nsss.py`
> 
> And what we are doing is we are replacing super() with objc.super()
> 
> **NOW JUST REMOVE ALL THE CODE FROM NSSS.PY AND JUST PASTE MINE**
> 
> copy paste from here: https://docs.google.com/document/d/1lCTSv6vCCXSLI_w55Bd43ExlLPQa8n2m5oesFFuFLQE/edit?usp=sharing
> 
> And if you are on global then do the same find nsss.py and replace its code and thank me later :)

Thanks!
Your code worked.
