### ISSUE TITLE
A bug when trying to get voices in MacOS

### ISSUE THREAD

**Issue by RojasAB** [nateshmbhat/pyttsx3#248]
I just fix it this way 
in **nsss.py** _toVoice just handle the age variable
![image](https://user-images.githubusercontent.com/52432007/202295019-291eef5c-54e6-4caa-806b-1f28291dfc78.png)

**Comment by Lodimup** [comment]
Same problem, comment out the age and it works.

**Comment by RobSchilderr** [comment]
I can not use this file in MacOS, its giving me [this error](https://stackoverflow.com/questions/71542305/python-text-to-voice-with-pyttsx3)

**Comment by cycleuser** [comment]
This can be solved by editing the 64th line of the nsss.py file.
simply remove the **attr['VoiceAge']** at this location will work.

Check the link below.

https://stackoverflow.com/questions/74668118/voiceage-error-while-using-pyttsx3-module-to-add-voice-to-statements/74727956#74727956

**Comment by andyvo190998** [comment]
how can i open nasss.py file?

**Comment by cycleuser** [comment]
> how can i open nasss.py file?

it locates at /opt/anaconda3/lib/python3.9/site-packages/pyttsx3/drivers/nsss.py  in my case.
you may need to find your site-packages location and then will be able to find it.

**Comment by Cre5cend0** [comment]
After commenting out the VoiceAge attribute, does anyone else have an issue with the speech voice? Mine appears to be corrupted and sounds highly distorted.

**Comment by willtonkin** [comment]
should be fixed once https://github.com/nateshmbhat/pyttsx3/pull/247 is merged 🤞🏻

**Comment by valeria-avila** [comment]
> After commenting out the VoiceAge attribute, does anyone else have an issue with the speech voice? Mine appears to be corrupted and sounds highly distorted.

Bruh, same here, I was so confused lmaooo
Did you ever find a way to fix it?
lmk, thanks!

**Comment by anth0nyhak1m** [comment]
It's 2024 and this issue still exists. Can someone please merge this fix?

**Comment by willwade** [comment]
99% sure fixed. Will triple check in a week
